remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

title: Matthew Wong
description: Data Science Portfolio
url: https://mathyoutw.github.io
baseurl: ""

author:
  name: "Matthew Wong"
  avatar: /assets/images/prof_pic.jpg

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-seo-tag
