remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "contrast"

description: Data Science Portfolio
url: https://mathyoutw.github.io
baseurl: ""

author:
  name: "Matthew Wong"
  avatar: /assets/images/prof_pic.jpg
  location: "San Diego, CA"
  github: mathyoutw
  linkedin: mathyoutw

collections:
  pages:
    output: true
    permalink: /:name/

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-seo-tag
